# Generated by Django 4.1.2 on 2022-12-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfExtractor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="news/"
                    ),
                ),
            ],
        ),
    ]
