# Generated by Django 4.1.4 on 2022-12-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfExtractor", "0003_alter_pdf_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PDF",
        ),
        migrations.AddField(
            model_name="text",
            name="file",
            field=models.FileField(default=None, null=True, upload_to="pdf/"),
        ),
        migrations.AlterField(
            model_name="text",
            name="des",
            field=models.TextField(default=None, null=True),
        ),
    ]
